using CompetitionManagementSystem.Models;

namespace CompetitionManagementSystem.Dtos.Participations;

public sealed record ParticipationResponse(
    Guid Id,
    Guid CompetitionId,
    string Platform,
    string ExternalPostId,
    string ExternalPostUrl,
    string Text,
    DateTime CreatedAtOnPlatformUtc,
    DateTime ImportedAtUtc,
    string AuthorUserName,
    string AuthorDisplayName,
    string? AuthorDescription,
    string? AuthorLocation,
    int AuthorFollowers,
    bool AuthorIsBlueVerified,
    int LikeCount,
    int RetweetCount,
    int ReplyCount,
    int QuoteCount,
    int ViewCount,
    bool IsReply,
    string? InReplyToId,
    bool IsActive,
    ParticipationStatus Status,
    string? ExclusionReason,
    bool IsAutoExcluded,
    bool HasVideo,
    bool HasPrimaryHashtag,
    bool HasSecondaryHashtag,
    string? ReservedByJudgeUserId,
    DateTime? ReservedAtUtc,
    string? ScoredByJudgeUserId,
    DateTime? ScoredAtUtc,
    string? CachedMediaUrlsJson,
    string? CachedPostSnapshotJson,
    bool IsManualTieWinner,
    string? TieSelectionReason,
    string? TieSelectedByUserId,
    DateTime? TieSelectedAtUtc,
    decimal FinalScore,
    int ScoreCount,
    DateTime? LastScoredAtUtc,
    // Populated only by the Judge "completed-by-me" endpoint and always limited to the
    // current authenticated judge's own ParticipationScores row. Null in every other context.
    Guid? ScoreId = null,
    decimal? Score = null,
    string? Notes = null,
    string? Justification = null);
